### ISSUE TITLE
License clarification?

### ISSUE THREAD

**Issue by justinclift** [UnfinishedBusiness/JetCAD3D#1]
From a [comment on Hacker News](https://news.ycombinator.com/item?id=21589203):

```
Could the license be clarified here? The code says its forked from SolveSpace which
indicated GPLv3, but JetCAD seems to have had the Copying.txt file and license
wording in the Readme removed?
```

**Comment by UnfinishedBusiness** [comment]
That was a mistake on my part. I deleted the Copying.txt file and meant to add LICENSE.md. It's fixed now and is licensed the same as SolveSpace, the GNU GPL V3.0 license.

@justinclift - Would you mind replying on Hacker News about this?

Thanks,
Travis

**Comment by justinclift** [comment]
No worries, done. :smile:

**Comment by UnfinishedBusiness** [comment]
Thank you!
